image: Ubuntu
version: '1.0.{build}'
configuration: Release
skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true
  
nuget:
  disable_publish_on_pr: true

environment:  
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  
build:
  project: ./src/db-migrate.csproj
  publish_nuget: false